console.log("Rodando o sistema de gerenciamento de jogos")
console.log("Rodando o sistema de gerenciamento de jogos2")
console.log("Rodando o sistema de gerenciamento de jogos3")
console.log("Rodando o sistema de gerenciamento de jogos4")
console.log("Rodando o sistema de gerenciamento de jogos5")
console.log("Enviando para o github")
